
// This file was auto-generated by ML.NET Model Builder. 

using MushroomModel_ConsoleApp;


// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Cap_shape = @"x",
    Cap_surface = @"s",
    Cap_color = @"y",
    Bruises = @"t",
    Odor = @"a",
    Gill_attachment = @"f",
    Gill_spacing = @"c",
    Gill_size = @"b",
    Gill_color = @"k",
    Stalk_shape = @"e",
    Stalk_root = @"c",
    Stalk_surface_above_ring = @"s",
    Stalk_surface_below_ring = @"s",
    Stalk_color_above_ring = @"w",
    Stalk_color_below_ring = @"w",
    Veil_type = @"p",
    Veil_color = @"w",
    Ring_number = @"o",
    Ring_type = @"p",
    Spore_print_color = @"n",
    Population = @"n",
    Habitat = @"g",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Class with predicted Class from sample data...\n\n");


Console.WriteLine($"Class: {@"e"}");
Console.WriteLine($"Cap_shape: {@"x"}");
Console.WriteLine($"Cap_surface: {@"s"}");
Console.WriteLine($"Cap_color: {@"y"}");
Console.WriteLine($"Bruises: {@"t"}");
Console.WriteLine($"Odor: {@"a"}");
Console.WriteLine($"Gill_attachment: {@"f"}");
Console.WriteLine($"Gill_spacing: {@"c"}");
Console.WriteLine($"Gill_size: {@"b"}");
Console.WriteLine($"Gill_color: {@"k"}");
Console.WriteLine($"Stalk_shape: {@"e"}");
Console.WriteLine($"Stalk_root: {@"c"}");
Console.WriteLine($"Stalk_surface_above_ring: {@"s"}");
Console.WriteLine($"Stalk_surface_below_ring: {@"s"}");
Console.WriteLine($"Stalk_color_above_ring: {@"w"}");
Console.WriteLine($"Stalk_color_below_ring: {@"w"}");
Console.WriteLine($"Veil_type: {@"p"}");
Console.WriteLine($"Veil_color: {@"w"}");
Console.WriteLine($"Ring_number: {@"o"}");
Console.WriteLine($"Ring_type: {@"p"}");
Console.WriteLine($"Spore_print_color: {@"n"}");
Console.WriteLine($"Population: {@"n"}");
Console.WriteLine($"Habitat: {@"g"}");


Console.WriteLine($"\n\nPredicted Class: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

